#ifndef INC_GPIO_H_
#define INC_GPIO_H_

#include "main.h"

#define BUTTON_ACCEPT_PORT		GPIOA
#define BUTTON_ACCEPT_PIN		GPIO_PIN_12
#define BUTTON_LEFT_PORT		GPIOA
#define BUTTON_LEFT_PIN			GPIO_PIN_11
#define BUTTON_RIGHT_PORT		GPIOB
#define BUTTON_RIGHT_PIN		GPIO_PIN_12
#define BUTTON_UP_PORT			GPIOB
#define BUTTON_UP_PIN			GPIO_PIN_11
#define BUTTON_DOWN_PORT		GPIOC
#define BUTTON_DOWN_PIN			GPIO_PIN_8

void gpio_init();


#endif /* INC_GPIO_H_ */
